name: DTUMisc
channels:
  - conda-forge
dependencies:
  - python>=3.9,<3.12 # cannot be over 3.11 as dtumathtools doesn't support that.
  - numpy
  - scipy
  - matplotlib
  - jupyterlab
  - notebook
  - pip
  - pip:
      - statsmodels
      - dtumathtools
      - pandas
      - sympy
      - plotly
